// All site content lives in this file. Edit a photo's title / subject / place /
// fieldNote / tags / favorite below; or add a new entry. Run scripts/sync-photos.py
// to regenerate from EXIF when you add new images.

export const profile = {
  name: "Affaan Kidwai",
  firstName: "Affaan",
  email: "kidwaiaffaan@gmail.com",
  linkedin: "https://www.linkedin.com/in/affaankidwai",
  role: "Associate Application Developer",
  company: "Oracle Financial Services Software",
  roleSince: "June 2024",
  hometown: "Lucknow, Uttar Pradesh",
  base: "Bengaluru, Karnataka",
  education: [
    {
      school: "SRM University",
      degree: "B.Tech, Computer Science with AIML specialisation",
      years: "2020 – 2024",
    },
    {
      school: "Delhi Public School, India",
      degree: "Class 12, PCM",
      years: "until 2020",
    },
  ],
  topSkills: [
    "Back-end web development",
    "Database management",
    "Oracle Database",
  ],
  skills: [
    "Back-end web development",
    "Database systems",
    "Oracle Database",
    "React",
    "Cloud operations",
    "Machine learning",
  ],
  certifications: [
    "Advanced React",
    "Web Development Bootcamp",
    "AWS Academy Cloud Operations",
    "Machine Learning A-Z",
    "Database Foundations",
  ],
};

// The "worlds" surfaced on the home page. Photography is live and links to the
// gallery; the rest are placeholders Affaan will fill in over time.
export const pursuits = [
  {
    slug: "photography",
    title: "Photography",
    eyebrow: "Wildlife · India",
    description:
      "Bengal tigers from the dry forest. Kingfishers in winter light. Paradise flycatchers through tangled branches. Frames I keep coming back to.",
    href: "/photography",
    cover: "/gallery/IMG_8409.jpg",
    status: "live",
    detail: "38 frames · 2024 – 25",
  },
  {
    slug: "tech",
    title: "Tech & Code",
    eyebrow: "Backend · Databases · Cloud",
    description: "Notes on Oracle, AWS, React, and the systems I work on by day.",
    status: "soon",
  },
  {
    slug: "travel",
    title: "Travel",
    eyebrow: "Forests · Cities · Roads",
    description:
      "Trip writing from across India and beyond — places, weather, and the small details.",
    status: "soon",
  },
  {
    slug: "cars",
    title: "Cars",
    eyebrow: "Engines · Roads · Drives",
    description:
      "A long-running interest. Drives, builds, and the engines that get me out of bed.",
    status: "soon",
  },
  {
    slug: "music",
    title: "Music",
    eyebrow: "Listening · Notes",
    description: "Albums I keep returning to and concerts that mattered.",
    status: "soon",
  },
  {
    slug: "cards",
    title: "Cards",
    eyebrow: "Games · Strategy",
    description: "The card games I play and the hands I won't forget.",
    status: "soon",
  },
];

export const photos = [
  {
    id: "IMG_0198",
    slug: "kingfisher-in-winter-light",
    title: "Kingfisher in winter light",
    subject: "White-throated Kingfisher",
    category: "Birds",
    place: "Northern wetland",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/6.3",
    iso: 2000,
    date: "2026-05-03",
    favorite: true,
    fieldNote: "He was hunting the same branch for an hour. The trick wasn't seeing him — it was waiting for the open beak.",
    tags: ["kingfisher", "bird", "winter"],
  },
  {
    id: "IMG_0243",
    slug: "img-0243",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/640s",
    aperture: "f/5.6",
    iso: 2000,
    date: "2026-05-03",
  },
  {
    id: "IMG_0244",
    slug: "img-0244",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/640s",
    aperture: "f/6.3",
    iso: 2500,
    date: "2026-05-03",
  },
  {
    id: "IMG_0257",
    slug: "img-0257",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "170mm",
    shutter: "1/640s",
    aperture: "f/5.6",
    iso: 1600,
    date: "2026-05-03",
  },
  {
    id: "IMG_0757",
    slug: "on-the-trail",
    title: "On the trail",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "Central India",
    width: 2400,
    height: 1547,
    camera: "Canon EOS R6 Mark II",
    lens: "RF200-800mm F6.3-9 IS USM",
    focal: "234mm",
    shutter: "1/1000s",
    aperture: "f/7.1",
    iso: 5000,
    date: "2024-03-04",
    featured: true,
    favorite: true,
    fieldNote: "A long, quiet morning. We waited at a bend in the road as the alarm calls thinned out. Then he just appeared — walking the same line he'd walked the day before, his pace not changing for us. The frame is from his second step into open light.",
    tags: ["tiger", "forest", "patrol", "morning"],
  },
  {
    id: "IMG_1927",
    slug: "img-1927",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "164mm",
    shutter: "1/800s",
    aperture: "f/5",
    iso: 160,
    date: "2024-06-02",
  },
  {
    id: "IMG_1934",
    slug: "img-1934",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "100mm",
    shutter: "1/800s",
    aperture: "f/6.3",
    iso: 100,
    date: "2024-06-02",
  },
  {
    id: "IMG_1942",
    slug: "songbird-in-willow",
    title: "Songbird in willow",
    subject: "Song Thrush",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/800s",
    aperture: "f/5.6",
    iso: 250,
    date: "2024-06-02",
    fieldNote: "Caught mid-song. The willow leaves moved more than the bird did.",
    tags: ["bird", "song", "willow"],
  },
  {
    id: "IMG_1956",
    slug: "img-1956",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "176mm",
    shutter: "1/1250s",
    aperture: "f/5",
    iso: 2000,
    date: "2024-06-02",
  },
  {
    id: "IMG_1988",
    slug: "img-1988",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "200mm",
    shutter: "1/1000s",
    aperture: "f/5.6",
    iso: 160,
    date: "2024-06-02",
  },
  {
    id: "IMG_2708",
    slug: "quiet-wait",
    title: "Quiet wait",
    subject: "Pond Heron",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/11",
    iso: 800,
    date: "2024-11-02",
    fieldNote: "A pond heron, almost the colour of the dry log. They wait better than we do.",
    tags: ["bird", "heron", "patience"],
  },
  {
    id: "IMG_3236",
    slug: "through-the-branches",
    title: "Through the branches",
    subject: "Indian Paradise Flycatcher",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "255mm",
    shutter: "1/1250s",
    aperture: "f/5.6",
    iso: 6400,
    date: "2025-05-02",
    favorite: true,
    fieldNote: "The white morph paradise flycatcher. He stayed for less than a minute, framed by leaves I couldn't move. I stopped down for depth and accepted the noise.",
    tags: ["bird", "rare", "monsoon"],
  },
  {
    id: "IMG_3252",
    slug: "img-3252",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/500s",
    aperture: "f/6.3",
    iso: 640,
    date: "2025-05-03",
  },
  {
    id: "IMG_3336",
    slug: "img-3336",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1250s",
    aperture: "f/5.6",
    iso: 250,
    date: "2025-05-03",
  },
  {
    id: "IMG_3861",
    slug: "forest-floor",
    title: "Forest floor",
    subject: "Bluethroat",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/160s",
    aperture: "f/5.6",
    iso: 2000,
    date: "2026-01-07",
    fieldNote: "Tiny, blink-and-miss-it. Settings on this one were imperfect, but the bird was there for less than a second.",
    tags: ["bird", "ground", "winter"],
  },
  {
    id: "IMG_4466",
    slug: "golden-hour-at-the-bank",
    title: "Golden hour at the bank",
    subject: "Ruddy Shelduck",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/800s",
    aperture: "f/5.6",
    iso: 400,
    date: "2026-01-09",
    fieldNote: "Bharatpur in late winter. The shelducks were paired up and the light was getting that warm rust colour you only get in January.",
    tags: ["bird", "duck", "winter"],
  },
  {
    id: "IMG_4834",
    slug: "img-4834",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/5.6",
    iso: 400,
    date: "2026-01-11",
  },
  {
    id: "IMG_7531",
    slug: "img-7531",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/400s",
    aperture: "f/5.6",
    iso: 500,
    date: "2026-04-06",
  },
  {
    id: "IMG_8346",
    slug: "img-8346",
    title: "",
    subject: "",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/6.3",
    iso: 500,
    date: "2024-03-04",
  },
  {
    id: "IMG_8364",
    slug: "into-the-light",
    title: "Into the light",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "Forest road",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "182mm",
    shutter: "1/200s",
    aperture: "f/5",
    iso: 1250,
    date: "2026-04-07",
    featured: true,
    fieldNote: "Walking straight down a sun-dappled track. He never looked at us, never broke stride. I dropped the shutter speed by accident and somehow it still worked.",
    tags: ["tiger", "forest", "morning"],
  },
  {
    id: "IMG_8409",
    slug: "eyes-of-the-dry-forest",
    title: "Eyes of the dry forest",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "Central India",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "271mm",
    shutter: "1/500s",
    aperture: "f/5",
    iso: 6400,
    date: "2026-04-07",
    featured: true,
    favorite: true,
    fieldNote: "A late-afternoon sighting — we were almost out of light. The tiger turned briefly to look at us and held the gaze for maybe two seconds. The forest was completely silent. ISO climbed but the moment was worth it.",
    tags: ["tiger", "portrait", "forest"],
  },
  {
    id: "IMG_8501",
    slug: "img-8501",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "312mm",
    shutter: "1/100s",
    aperture: "f/5.6",
    iso: 2000,
    date: "2026-04-07",
  },
  {
    id: "IMG_8579",
    slug: "the-slow-approach",
    title: "The slow approach",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 1600,
    height: 2400,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "135mm",
    shutter: "1/250s",
    aperture: "f/5",
    iso: 5000,
    date: "2026-05-02",
    fieldNote: "She walked toward us for thirty seconds before any of us breathed. I shot vertical because horizontal felt rude.",
    tags: ["tiger", "vertical", "approach"],
  },
  {
    id: "IMG_8686",
    slug: "img-8686",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/200s",
    aperture: "f/5.6",
    iso: 2000,
    date: "2026-05-02",
  },
  {
    id: "IMG_8761",
    slug: "a-long-yawn",
    title: "A long yawn",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "Ranthambore",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "255mm",
    shutter: "1/500s",
    aperture: "f/5.6",
    iso: 5000,
    date: "2026-05-02",
    featured: true,
    favorite: true,
    fieldNote: "Mid-morning rest, but the tiger stretched and yawned for what felt like forever. The fangs and tongue against the dust track is one of those moments you only see in person every once in a while.",
    tags: ["tiger", "behaviour", "rest"],
  },
  {
    id: "IMG_8880",
    slug: "resting-pair",
    title: "Resting pair",
    subject: "Bengal Tigers",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "148mm",
    shutter: "1/1000s",
    aperture: "f/5",
    iso: 1250,
    date: "2026-05-02",
    fieldNote: "Mid-morning heat. They had picked the only patch of shade for half a kilometre and weren't going anywhere.",
    tags: ["tigers", "rest", "midday"],
  },
  {
    id: "IMG_8938",
    slug: "img-8938",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/5.6",
    iso: 800,
    date: "2026-05-02",
  },
  {
    id: "IMG_8986",
    slug: "img-8986",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/800s",
    aperture: "f/6.3",
    iso: 500,
    date: "2026-05-02",
  },
  {
    id: "IMG_9036-2",
    slug: "img-9036-2",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "234mm",
    shutter: "1/800s",
    aperture: "f/5",
    iso: 2000,
    date: "2026-05-02",
  },
  {
    id: "IMG_9036",
    slug: "img-9036",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "234mm",
    shutter: "1/800s",
    aperture: "f/5",
    iso: 2000,
    date: "2026-05-02",
  },
  {
    id: "IMG_9101",
    slug: "img-9101",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/1000s",
    aperture: "f/6.3",
    iso: 160,
    date: "2026-05-02",
  },
  {
    id: "IMG_9342",
    slug: "two-by-the-water",
    title: "Two by the water",
    subject: "Bengal Tigers",
    category: "Tigers",
    place: "Lakeside grassland",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/500s",
    aperture: "f/6.3",
    iso: 1600,
    date: "2026-05-03",
    featured: true,
    fieldNote: "The two of them came down to the lake at dawn and just sat. We watched from the far bank for almost forty minutes. They never made eye contact with each other, just shared the silence.",
    tags: ["tigers", "lake", "dawn"],
  },
  {
    id: "IMG_9458",
    slug: "img-9458",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/320s",
    aperture: "f/5.6",
    iso: 1000,
    date: "2026-05-03",
  },
  {
    id: "IMG_9492",
    slug: "among-the-red-bushes",
    title: "Among the red bushes",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "Ranthambore foothills",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/640s",
    aperture: "f/6.3",
    iso: 2000,
    date: "2026-05-03",
    featured: true,
    favorite: true,
    fieldNote: "The undergrowth was already turning. The tiger came down the slope quietly, stepped into the bushes, and stopped exactly where the light caught the foliage. Sometimes you barely click — you just hold your breath.",
    tags: ["tiger", "color", "evening"],
  },
  {
    id: "IMG_9552",
    slug: "img-9552",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "255mm",
    shutter: "1/800s",
    aperture: "f/5.6",
    iso: 3200,
    date: "2026-05-03",
  },
  {
    id: "IMG_9574",
    slug: "img-9574",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "248mm",
    shutter: "1/800s",
    aperture: "f/5.6",
    iso: 1600,
    date: "2026-05-03",
  },
  {
    id: "IMG_9585-2",
    slug: "img-9585-2",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "100mm",
    shutter: "1/800s",
    aperture: "f/5",
    iso: 1250,
    date: "2026-05-03",
  },
  {
    id: "IMG_9585",
    slug: "img-9585",
    title: "",
    subject: "Bengal Tiger",
    category: "Tigers",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "100mm",
    shutter: "1/800s",
    aperture: "f/5",
    iso: 1250,
    date: "2026-05-03",
  },
  {
    id: "IMG_9744",
    slug: "stones-and-shore",
    title: "Stones and shore",
    subject: "Great Stone-curlew",
    category: "Birds",
    place: "",
    width: 2400,
    height: 1600,
    camera: "Canon EOS 70D",
    lens: "EF100-400mm f/4.5-5.6L IS II USM",
    focal: "400mm",
    shutter: "1/640s",
    aperture: "f/6.3",
    iso: 125,
    date: "2026-05-03",
    fieldNote: "Stone-curlew on a riverbank. They are absurdly hard to see when they don't want to be seen.",
    tags: ["bird", "shore", "camouflage"],
  },
];

// --- Photo helpers ---

export function photoSrc(photo) {
  return `/gallery/${photo.id}.jpg`;
}

export function photoLabel(photo, index) {
  if (photo.title) return photo.title;
  return `Frame ${String(index + 1).padStart(2, "0")}`;
}

export function getPhotoBySlug(slug) {
  return photos.find((p) => p.slug === slug);
}

export function getPhotoNeighbours(slug) {
  const i = photos.findIndex((p) => p.slug === slug);
  if (i < 0) return { prev: null, next: null };
  const prev = i > 0 ? photos[i - 1] : photos[photos.length - 1];
  const next = i < photos.length - 1 ? photos[i + 1] : photos[0];
  return { prev, next };
}

export function formatPhotoDate(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

// --- Curated subsets ---

export const featuredPhotos = photos.filter((p) => p.featured);
export const favoritePhotos = photos.filter((p) => p.favorite);

// The single static hero image on the home page. Change this `id` to swap.
export const heroPhoto =
  photos.find((p) => p.id === "IMG_0757") ?? photos[0];

// The standout image Featured Frame on home points to.
export const featuredFrame =
  photos.find((p) => p.slug === "on-the-trail") ?? photos[0];

// Categories present in the gallery, in display order.
const categoryOrder = ["Tigers", "Birds", "Wildlife"];
export const photoCategories = Array.from(
  new Set(photos.map((p) => p.category).filter(Boolean)),
).sort((a, b) => {
  const ia = categoryOrder.indexOf(a);
  const ib = categoryOrder.indexOf(b);
  if (ia === -1 && ib === -1) return a.localeCompare(b);
  if (ia === -1) return 1;
  if (ib === -1) return -1;
  return ia - ib;
});
